"""OAuth2 client for Bling API v3 token endpoints."""

from __future__ import annotations

from typing import TYPE_CHECKING, Self
from urllib.parse import urlencode

import httpx

from bling_jwt_auth.constants import (
    ACCEPT_HEADER_VALUE,
    ENABLE_JWT_HEADER,
    ENABLE_JWT_VALUE,
)
from bling_jwt_auth.exceptions import OAuthRequestError
from bling_jwt_auth.models.token import TokenResponse

if TYPE_CHECKING:
    from bling_jwt_auth.config import BlingAuthSettings


class OAuthClient:
    """Synchronous client for Bling OAuth endpoints.

    The client handles the HTTP details required by Bling's API v3 OAuth flow:
    authorization URL generation, code exchange, refresh-token grant, optional
    token revocation, Basic authentication with client credentials, and the
    ``enable-jwt`` compatibility header when configured.

    Pass an existing ``httpx.Client`` when your application owns connection
    pooling. Otherwise this class creates one and closes it when used as a
    context manager or when :meth:`close` is called.
    """

    def __init__(
        self,
        settings: BlingAuthSettings,
        *,
        client: httpx.Client | None = None,
        timeout: float = 30.0,
    ) -> None:
        """Initialize the OAuth client.

        Args:
            settings: Bling OAuth configuration.
            client: Optional preconfigured ``httpx.Client``. When omitted, a
                new client is created and owned by this instance.
            timeout: Timeout used only when this instance creates the HTTP
                client internally.
        """
        self._settings = settings
        self._owns_client = client is None
        self._client = client or httpx.Client(timeout=timeout)

    @property
    def settings(self) -> BlingAuthSettings:
        """Settings used for endpoint URLs, credentials, and JWT header behavior."""
        return self._settings

    def close(self) -> None:
        """Close the underlying HTTP client if it is owned by this instance."""
        if self._owns_client:
            self._client.close()

    def __enter__(self) -> Self:
        """Begin a context-managed session (no-op besides returning ``self``)."""
        return self

    def __exit__(self, *_exc: object) -> None:
        """Ensure the underlying client is closed when exiting the context."""
        self.close()

    def build_authorization_url(self, state: str) -> str:
        """Build the browser URL that starts the Bling authorization flow.

        Args:
            state: Non-empty CSRF correlation value generated by the caller.

        Returns:
            Absolute Bling authorization URL with ``response_type=code``,
            ``client_id``, ``redirect_uri``, and ``state`` query parameters.

        Raises:
            ValueError: If ``state`` is empty.
        """
        if not state:
            msg = "state must be a non-empty string"
            raise ValueError(msg)
        params = {
            "response_type": "code",
            "client_id": self._settings.client_id,
            "state": state,
            "redirect_uri": str(self._settings.redirect_uri),
        }
        return f"{self._settings.authorize_url}?{urlencode(params)}"

    def exchange_code(self, code: str) -> TokenResponse:
        """Exchange a callback authorization code for OAuth tokens.

        Args:
            code: The ``code`` query parameter received by your redirect URI.

        Raises:
            ValueError: If ``code`` is empty.
            OAuthRequestError: If Bling returns a non-success HTTP response or
                an unexpected token response shape.
        """
        if not code:
            msg = "code must be a non-empty string"
            raise ValueError(msg)
        data = {
            "grant_type": "authorization_code",
            "code": code,
        }
        return self._post_token(data)

    def refresh_token(self, refresh_token: str) -> TokenResponse:
        """Refresh credentials using a stored refresh token.

        Args:
            refresh_token: Refresh token from a previous successful token
                response.

        Raises:
            ValueError: If ``refresh_token`` is empty.
            OAuthRequestError: If Bling returns a non-success HTTP response or
                an unexpected token response shape.
        """
        if not refresh_token:
            msg = "refresh_token must be a non-empty string"
            raise ValueError(msg)
        data = {
            "grant_type": "refresh_token",
            "refresh_token": refresh_token,
        }
        return self._post_token(data)

    def revoke_token(
        self,
        token: str,
        *,
        token_type_hint: str | None = None,
    ) -> None:
        """Revoke an access token or refresh token at Bling.

        Args:
            token: Token value to revoke.
            token_type_hint: Optional OAuth hint such as ``access_token`` or
                ``refresh_token``.

        Raises:
            ValueError: If ``token`` is empty.
            OAuthRequestError: If Bling returns a non-success HTTP response.
        """
        if not token:
            msg = "token must be a non-empty string"
            raise ValueError(msg)
        data: dict[str, str] = {"token": token}
        if token_type_hint is not None:
            data["token_type_hint"] = token_type_hint
        response = self._client.post(
            str(self._settings.revoke_url),
            data=data,
            headers=self._oauth_headers(),
            auth=httpx.BasicAuth(
                self._settings.client_id,
                self._settings.client_secret.get_secret_value(),
            ),
        )
        self._raise_for_status(response)

    def _oauth_headers(self) -> dict[str, str]:
        headers = {
            "Content-Type": "application/x-www-form-urlencoded",
            "Accept": ACCEPT_HEADER_VALUE,
        }
        if self._settings.enable_jwt:
            headers[ENABLE_JWT_HEADER] = ENABLE_JWT_VALUE
        return headers

    def _post_token(self, data: dict[str, str]) -> TokenResponse:
        response = self._client.post(
            str(self._settings.token_url),
            data=data,
            headers=self._oauth_headers(),
            auth=httpx.BasicAuth(
                self._settings.client_id,
                self._settings.client_secret.get_secret_value(),
            ),
        )
        self._raise_for_status(response)
        payload = response.json()
        if not isinstance(payload, dict):
            msg = "Unexpected token response: JSON object expected"
            raise OAuthRequestError(
                msg, status_code=response.status_code, response_body=response.text
            )
        return TokenResponse.model_validate(payload)

    def _raise_for_status(self, response: httpx.Response) -> None:
        if response.is_success:
            return
        msg = f"OAuth request failed with HTTP {response.status_code}"
        raise OAuthRequestError(
            msg,
            status_code=response.status_code,
            response_body=response.text,
        )
